### ISSUE TITLE
BadFetchError causes session to close

### ISSUE THREAD

**Issue by srikrishnacj** [JVoiceXML/JVoiceXML#10]
I just coped only required jvoicexml core projects ( required\* - as specified in how to build guide ) into intellij Idea project. I am using JVoiceXml in embedded mode so i created an instance of JVoiceXmlMain and started it manually. and I did not use JNDI. I am creating session like this

ConnectionInformation info = new BasicConnectionInformation("text", "text", "text");

since implementation.text using Socket to interact with JVoiceXML, i just commented all the  text telephony code and inserted print statements. once the record method is called on text telephone object, i just inject string "1" as

TextSpokenInput textSpokenInput = (TextSpokenInput) input;
textSpokenInput.notifyRecognitionResult("1");

While verifying DTMF result i found that no grammar checkers are available and it cause the re-prompt. the re-prompt is answered like before, now the expection is thrown and session is being closed

org.jvoicexml.event.plain.implementation.NomatchEvent: nomatch
[jvoicexml.txt](https://github.com/JVoiceXML/JVoiceXML/files/127955/jvoicexml.txt)

Log file Location
http://pastebin.com/GtVvAfMb

Modified TextTelephony.java
http://pastebin.com/EeGp5Mhr

please help me to find what i am doing wrong.
is there email group for this project to ask help?

**Comment by srikrishnacj** [comment]
This time i used DtmfInput from session to send DTMF input. when i send corrent input it goes to next form element. if i send wrong DTMF more than 2 times, it throws org.jvoicexml.event.error.BadFetchError: error.badfetch: unhandled event 'nomatch' and closes the session.

**Comment by schnelle** [comment]
Hmmm...a lot of jars are not found. Can you send me an email to dirk (dot) schnelle (at) jvoicexml (dot) org. Maybe, this is more direct to get you started.

An email group existed but I shut it down since there was no traffic on it.

**Comment by schnelle** [comment]
Should be fixed with the latest changes of the text platform. Please verify.

**Comment by schnelle** [comment]
Closing, as they were no further comments.
