### ISSUE TITLE
Support for vertx

### ISSUE THREAD

**Issue by rapgro** [JVoiceXML/JVoiceXML#104]
Please take a look into Vert.x, part of the Eclipse project. It could help to implement a common protocol for all the interactions requested to other languages and technologies outside of Java only like Python, AMQP (#96 ) etc.
https://vertx.io/

Looking forward to read about comments what people of the JVoiceXML community think.

**Comment by schnelle** [comment]
Could you provide me with a concrete example how you think it could be utilized?

**Comment by rapgro** [comment]
Well, the underlying protocol seems to be based on HTTP. Please take a look into official documentation.
https://vertx.io/docs/vertx-core/java/

**Comment by schnelle** [comment]
Too unspecific to consider for future development.

**Comment by rapgro** [comment]
Kubernetes is too unspecific?
https://www.micromata.de/blog/softwareentwicklung/vert-x-eventbus-kubernetes/

**Comment by schnelle** [comment]
No, you use case is too unspecific. I still do not understand what it shall be used for and what you have in mind. I asked for it, but I did not get any meaningful answer.

**Comment by rapgro** [comment]
Improved IPC. https://www.geeksforgeeks.org/inter-process-communication-ipc/

**Comment by schnelle** [comment]
IPC is only used in case of JNDI which is only there to be able to access the voice browser in absense of any telephony environment.

What are the benefits you are exepcting from this over JNDI?

**Comment by rapgro** [comment]
JNDI is very specific to Java only. A more common IPC would allow other programming languages, e.g. vertx provides several bindings.
