### ISSUE TITLE
protobuf

### ISSUE THREAD

**Issue by rapgro** [JVoiceXML/JVoiceXML#11]
"TextMessage.proto: TextMessage.proto: Cannot generate Java output because the file's outer class name, "TextMessage", matches the name of one of the types declared inside it. Please either rename the type or use the java_outer_classname option to specify a different outer class name for the .proto file."

The fix is simple. Please apply in GitHub, I did in my GitLab.
https://gitlab.com/rapgro/jvoicexml/commit/82198c4554cd496450af7fb77bc226b24c98a253#diff-0

org.jvoicexml.client.text/etc/proto/TextMessage.proto 
`option java_outer_classname = "TextMessageOuterClass";`

**Comment by schnelle** [comment]
I have no issues with that. This works for me

**Comment by rapgro** [comment]
> The java_outer_classname option defines the class name which should contain all of the classes in this file. If you don't give a java_outer_classname explicitly, it will be generated by converting the file name to camel case. For example, "my_proto.proto" would, by default, use "MyProto" as the outer class name. 
https://developers.google.com/protocol-buffers/docs/javatutorial#defining-your-protocol-format

I assume the default of generator behavior is different on your side.
