### ISSUE TITLE
Text platform sometimes sends empty queue too early

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#113]
Sometimes the text platform sends an empty queue event before the addition of new prompts. This may result in termination of the document interpretation.

**Comment by rapgro** [comment]
Again, I suggest to blame synchronization over native sockets. Please consider to change implementation to work over a higher level of protocol abstraction. RabbitMQ has a well tested message pipe and isn't known to randomly forget any entry and works smoothly in message queuing. That was one of initial ideas years ago when we started to implement the test framework.

**Comment by schnelle** [comment]
First analysis shows that this is not caused by the protocol but a wrong implementation of https://www.w3.org/TR/voicexml20/#dml4.1.8. so this could be potentially observable in all platforms.

The queue is emptied immediately in the current implementation but playing back prompts must wait until the transition phase had ended.
