### ISSUE TITLE
Supported Java version

### ISSUE THREAD

**Issue by rapgro** [JVoiceXML/JVoiceXML#12]
We still support Java 7 and 8. I noticed both CentOS 7.8 and 6 have now Java 8. If we want Java 7, there's CentOS 5 to use. May be worth to rethink about dropping (legacy) support for Java 7 and enforce Java 8.

**Comment by schnelle** [comment]
Enforcing Java 8 may cause some trouble on Android. See https://developer.android.com/guide/platform/j8-jack.html

I will do it, once this is solved.

**Comment by rapgro** [comment]
For me, that means: Developing with Java 8 on a current system (e.g. Fedora 25 / CentOS 7) and testing for Java 7 on an outdated system (CentOS 5). Interesting!
The linked article does not say Java 8 is not possible on Android. It talks about some features are not available of Java 8. We currently do not use any Java 8 features.

**Comment by schnelle** [comment]
It is still problematic to some degree to use Java 8 on Android. I feel that this should be fixed before moving to Java 8 completely. That is what I stated.

It is up to you, to manage your Java runtime configurations correctly..
