### ISSUE TITLE
Remove abandandonned projects

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#125]
Several projects exist in the JVoiceXML repository that are no longer used or did not advance beyond a template. These ought to be removed.

**Comment by schnelle** [comment]
Removing projects

- org.jvoicexml.callmanager.mmi.umundo
- org.jvoicexml.demo.marcdemo
- org.jvoicexml.interpreter.grammar.halef
- org.jvoicexml.implementation.kinect
- org.jvoicexml.implementation.marc
- org.jvoicexml.implementation.mobicents
- org.jvoicexml.implementation.jsapi10
- org.jvoicexml.implementation.red5

**Comment by schnelle** [comment]
projects are still in develop branch

**Comment by rapgro** [comment]
SCNR https://gist.github.com/lolzballs/2152bc0f31ee0286b722
