### ISSUE TITLE
Hangup event should terminate FIA processing and enter the final processing state

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#128]
Currently, JVoiceXML continues processing until a current transition state has ended. This violated the specification to enter the final processing state in these cases.
See also https://www.w3.org/TR/voicexml20/#dml1.5.4
This depends on #127

**Comment by rapgro** [comment]
Another reason why to use message queue like RabbitMQ.

**Comment by schnelle** [comment]
Sorry, but this is completely unrelated to the issue here.

**Comment by schnelle** [comment]
Terminating FIA processing is not required and did not seem to be possible with Java does not allow to inject events into other threads. Jave relies more on a cooperative way among threads. The thread is asked to terminate and the thread can then shutdown gracefully.

Hence, this issue will focus on cleaning processing up for the final processing stage.
