### ISSUE TITLE
Adapt DocumentStorage to the SessionIdentifier object

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#129]
The Jetty Document Storage uses the SessionIdentifier.toString() method to identify the session but should rely on the SessionIdentifier.getId() method instead to also accomodate to the change from a String based session identifier to an object.

**Comment by rapgro** [comment]
Where's implementation of SessionIdentifier as a class? For a quick search I find HttpClientSessionIdentifierFactory only but the constructor ignores sessionId as parameter.

https://github.com/JVoiceXML/JVoiceXML/blob/8b14da8dca4f480e71a5abb10ee6a7c96e09450c/org.jvoicexml/src/main/java/org/jvoicexml/documentserver/schemestrategy/HttpClientSessionIdentifierFactory.java#L58

**Comment by schnelle** [comment]
This is referring to https://github.com/JVoiceXML/JVoiceXML/blob/develop/org.jvoicexml/src/main/java/org/jvoicexml/SessionIdentifier.java

**Comment by rapgro** [comment]
> This is referring to https://github.com/JVoiceXML/JVoiceXML/blob/develop/org.jvoicexml/src/main/java/org/jvoicexml/SessionIdentifier.java

Ok, then sorry about GitHub search tried to fool me.

**Comment by roberto-cisternino** [comment]
Sorry for asking so late.... but JVoiceXml is not independent from a specific application server,. Why there is a binding to Jetty ? Also the guidelines are talking about Tomcat.  Best

**Comment by schnelle** [comment]
Jetty is just used as an example implementation of a DocumentServer. It is separated into an own project. JVoiceXML can be configured to use any other implementation.
So, yes, there is a dependency if you stick to this implementation.

**Comment by roberto-cisternino** [comment]
Well the library where jetty is invokated is one of the main jars. So do you mean that I must implemnt a different documentStorage and change the jvoicexml.xml settings below ? Or do you mean to skip the whole org.jvoicexml.documentserver.* implementation ?

    <property name="documentStorage">
        <bean class="org.jvoicexml.documentserver.jetty.DocumentStorage">
            
            
            
            <property name="storagePort" value="9595" />
            <property name="grammarCreators">
                <list>
                    <bean class="org.jvoicexml.documentserver.schemestrategy.builtin.BooleanGrammarCreator"/>
                    <bean class="org.jvoicexml.documentserver.schemestrategy.builtin.DigitsGrammarCreator"/>
                </list>
            </property>
        </bean>
    </property>

**Comment by schnelle** [comment]
Are you using the latest snapshot from the develop branch?

There, it should be decoupled and loaded from the configuration into the document server. It will locate the configuration file for the Jetty based implementation in the config folder. 

However, the Document storage based on Jetty is the only implantation that is offered so far. Which one would you prefer to have? File based may be another generic option.

**Comment by roberto-cisternino** [comment]
Hello, I am using the 0.7.8 version, but I initially downloaded the package. So I should get it from GIT right ?
About the app server  I would tend to use a full J2EE server such as Payara and I would prefere to follow the servlet specification as I am not fond of Jetty specific handlers, contexts, so on.
Moreover, my opinion is that the app server shoudl be an existing one without the need of embedding and having JVoiceXml to start/stop the server.  Thank you for your suggestions.

**Comment by roberto-cisternino** [comment]
Hello, yes the file based storage can be easier.
In general I would need just a JVoiceXML API.  I find difficult the integration. I use a J2EE application server where jndi is already integrated, that's why I would need just to rely on a plain API.

Also I tried using the last development snapshot but there is a building issue in jsapi20:

JAVA_HOME="C:\Program Files\Java\jdk1.8.0_212"
cd E:\DEV\git\JVoiceXML\org.jvoicexml.implementation.jsapi20; ..\gradlew.bat --configure-on-demand -x check clean build
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Script 'E:\DEV\git\JVoiceXML\org.jvoicexml.implementation.jsapi20\build.gradle' line: 57

* What went wrong:
A problem occurred evaluating project ':org.jvoicexml.implementation.jsapi20'.
> Could not get unknown property 'copyConfiguration' for project ':org.jvoicexml' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 155ms

**Comment by schnelle** [comment]
This following works for me 
gradlew clean installDist

Please create another issue to follow up in case you still have issues as this exceeds the topic of this issue.

Regarding JNDI: This not mandatory to use but currently it starts up its own stuff. Please create another issue if you want to use your own J(2)EE server for this.

**Comment by schnelle** [comment]
In case you have issues to set up the build environment, I could also offer to prepare a snapshot for you. Just send me an email.
