### ISSUE TITLE
The build of the latest dev snapshot is successful but mary jar is missing

### ISSUE THREAD

**Issue by roberto-cisternino** [JVoiceXML/JVoiceXML#150]
The mary jar "org.jvoicexml.implementation.mary-@@VERSION@@.jar" is missing even if the build is successfull.

JAVA_HOME="C:\Program Files\Java\jdk1.8.0_212"
cd E:\DEV\git\JVoiceXML\main; ..\gradlew.bat --configure-on-demand -x check clean build
Configuration on demand is an incubating feature.
> Task :org.jvoicexml:clean
> Task :main:clean
> Task :main:customDistTar NO-SOURCE
> Task :main:customDistZip NO-SOURCE
> Task :main:compileJava NO-SOURCE
> Task :main:processResources NO-SOURCE
> Task :main:classes UP-TO-DATE
> Task :main:jar SKIPPED
> Task :org.jvoicexml.xml:compileJava UP-TO-DATE
> Task :org.jvoicexml:compileJava
> Task :org.jvoicexml:processResources
> Task :org.jvoicexml:classes
> Task :org.jvoicexml:createVersionFile
> Task :org.jvoicexml:copyConfigurationDistribution
> Task :org.jvoicexml:enableLog4jRemoteAppenderDistribution
> Task :org.jvoicexml:copyConfiguration
> Task :org.jvoicexml:enableLog4jRemoteAppender
> Task :org.jvoicexml:renameLog4jRemoteAppender
> Task :org.jvoicexml:jar
> Task :org.jvoicexml.config:compileJava UP-TO-DATE
> Task :org.jvoicexml.config:processResources UP-TO-DATE
> Task :org.jvoicexml.config:classes UP-TO-DATE
> Task :org.jvoicexml.config:copyConfiguration
> Task :org.jvoicexml.config:copyConfigurationDistribution
> Task :org.jvoicexml.config:jar
> Task :org.jvoicexml.srgs:compileJava UP-TO-DATE
> Task :org.jvoicexml.srgs:processResources NO-SOURCE
> Task :org.jvoicexml.srgs:classes UP-TO-DATE
> Task :org.jvoicexml.srgs:jar
> Task :org.jvoicexml.xml:processResources NO-SOURCE
> Task :org.jvoicexml.xml:classes UP-TO-DATE
> Task :org.jvoicexml.xml:jar
> Task :main:createShutdownApp
> Task :org.jvoicexml.callmanager.mmi.servlet:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.servlet:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.mmi.servlet:classes UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.servlet:explodedWar
> Task :org.jvoicexml.callmanager.mmi.servlet:war
> Task :main:jvxmlServlet
> Task :main:startScripts
> Task :org.jvoicexml.client:compileJava UP-TO-DATE
> Task :org.jvoicexml.mmi.events:extractIncludeProto UP-TO-DATE
> Task :org.jvoicexml.mmi.events:extractProto UP-TO-DATE
> Task :org.jvoicexml.mmi.events:generateProto UP-TO-DATE
> Task :org.jvoicexml.mmi.events:compileJava UP-TO-DATE
> Task :org.jvoicexml.profile.vxml21:compileJava UP-TO-DATE
> Task :org.jvoicexml.profile.mmi:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.mmi:classes UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi:jar
> Task :org.jvoicexml.callmanager.mmi.http:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.http:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.mmi.http:classes UP-TO-DATE
> Task :org.jvoicexml.client:processResources UP-TO-DATE
> Task :org.jvoicexml.client:classes UP-TO-DATE
> Task :org.jvoicexml.client:jar
> Task :org.jvoicexml.mmi.events:processResources UP-TO-DATE
> Task :org.jvoicexml.mmi.events:classes UP-TO-DATE
> Task :org.jvoicexml.mmi.events:jar
> Task :org.jvoicexml.profile.mmi:processResources NO-SOURCE
> Task :org.jvoicexml.profile.mmi:classes UP-TO-DATE
> Task :org.jvoicexml.profile.vxml21:processResources NO-SOURCE
> Task :org.jvoicexml.profile.vxml21:classes UP-TO-DATE
> Task :org.jvoicexml.profile.vxml21:xslt
> Task :org.jvoicexml.profile.vxml21:xsltDistribution
> Task :org.jvoicexml.profile.vxml21:jar
> Task :org.jvoicexml.profile.mmi:copyReferencedLibraries
> Task :org.jvoicexml.profile.mmi:xslt
> Task :org.jvoicexml.profile.mmi:xsltDistribution
> Task :org.jvoicexml.profile.mmi:jar
> Task :org.jvoicexml.callmanager.mmi.http:copyReferencedLibraries
> Task :org.jvoicexml.callmanager.mmi.http:xslt
> Task :org.jvoicexml.callmanager.mmi.http:xsltDistribution
> Task :org.jvoicexml.callmanager.mmi.http:jar
> Task :org.jvoicexml.callmanager.mmi.servlet:jar UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.socket:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.socket:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.mmi.socket:classes UP-TO-DATE
> Task :org.jvoicexml.callmanager.mmi.socket:copyReferencedLibraries
> Task :org.jvoicexml.callmanager.mmi.socket:xslt
> Task :org.jvoicexml.callmanager.mmi.socket:xsltDistribution
> Task :org.jvoicexml.callmanager.mmi.socket:jar
> Task :org.jvoicexml.client.mrcpv2:compileJava UP-TO-DATE
> Task :org.jvoicexml.zanzibar:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.sip:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.sip:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.sip:classes UP-TO-DATE
> Task :org.jvoicexml.client.mrcpv2:processResources NO-SOURCE
> Task :org.jvoicexml.client.mrcpv2:classes UP-TO-DATE
> Task :org.jvoicexml.client.mrcpv2:jar
> Task :org.jvoicexml.zanzibar:processResources UP-TO-DATE
> Task :org.jvoicexml.zanzibar:classes UP-TO-DATE
> Task :org.jvoicexml.zanzibar:jar
> Task :org.jvoicexml.callmanager.sip:copyReferencedLibraries
> Task :org.jvoicexml.callmanager.sip:xsltCallmanager
> Task :org.jvoicexml.callmanager.sip:xsltCallmanagerDistribution
> Task :org.jvoicexml.callmanager.sip:jar
> Task :org.jvoicexml.client.text:extractIncludeProto UP-TO-DATE
> Task :org.jvoicexml.client.text:extractProto UP-TO-DATE
> Task :org.jvoicexml.client.text:generateProto UP-TO-DATE
> Task :org.jvoicexml.client.text:compileJava UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.luis:compileJava UP-TO-DATE
> Task :org.jvoicexml.implementation.text:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.text:compileJava UP-TO-DATE
> Task :org.jvoicexml.callmanager.text:processResources NO-SOURCE
> Task :org.jvoicexml.callmanager.text:classes UP-TO-DATE
> Task :org.jvoicexml.client.text:processResources UP-TO-DATE
> Task :org.jvoicexml.client.text:classes UP-TO-DATE
> Task :org.jvoicexml.client.text:jar
> Task :org.jvoicexml.implementation.text:processResources NO-SOURCE
> Task :org.jvoicexml.implementation.text:classes UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.luis:processResources UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.luis:classes UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.luis:copyReferencedLibraries NO-SOURCE
> Task :org.jvoicexml.interpreter.grammar.luis:xslt
> Task :org.jvoicexml.interpreter.grammar.luis:xsltDistribution
> Task :org.jvoicexml.interpreter.grammar.luis:jar
> Task :org.jvoicexml.implementation.text:copyReferencedLibraries
> Task :org.jvoicexml.implementation.text:xslt
> Task :org.jvoicexml.implementation.text:xsltDistribution
> Task :org.jvoicexml.implementation.text:jar
> Task :org.jvoicexml.callmanager.text:copyReferencedLibraries
> Task :org.jvoicexml.callmanager.text:xslt
> Task :org.jvoicexml.callmanager.text:xsltDistribution
> Task :org.jvoicexml.callmanager.text:jar
> Task :org.jvoicexml.documentserver.schemestrategy.file:compileJava UP-TO-DATE
> Task :org.jvoicexml.documentserver.schemestrategy.file:processResources NO-SOURCE
> Task :org.jvoicexml.documentserver.schemestrategy.file:classes UP-TO-DATE
> Task :org.jvoicexml.documentserver.schemestrategy.file:xslt
> Task :org.jvoicexml.documentserver.schemestrategy.file:xsltDistribution
> Task :org.jvoicexml.documentserver.schemestrategy.file:jar
> Task :org.jvoicexml.documentserver.schemestrategy.http:compileJava UP-TO-DATE
> Task :org.jvoicexml.documentserver.schemestrategy.http:processResources NO-SOURCE
> Task :org.jvoicexml.documentserver.schemestrategy.http:classes UP-TO-DATE
> Task :org.jvoicexml.documentserver.schemestrategy.http:copyReferencedLibraries UP-TO-DATE
> Task :org.jvoicexml.documentserver.schemestrategy.http:xsltDistributionHttp
> Task :org.jvoicexml.documentserver.schemestrategy.http:xsltDistributionHttps
> Task :org.jvoicexml.documentserver.schemestrategy.http:xsltHttp
> Task :org.jvoicexml.documentserver.schemestrategy.http:xsltHttps
> Task :org.jvoicexml.documentserver.schemestrategy.http:jar
> Task :org.jvoicexml.implementation.jsapi20:compileJava UP-TO-DATE
> Task :org.jvoicexml.implementation.jsapi20:processResources NO-SOURCE
> Task :org.jvoicexml.implementation.jsapi20:classes UP-TO-DATE
> Task :org.jvoicexml.implementation.jsapi20:copyReferencedLibraries UP-TO-DATE
> Task :org.jvoicexml.implementation.jsapi20:copyJNI
> Task :org.jvoicexml.implementation.jsapi20:xsltSAPI SKIPPED
> Task :org.jvoicexml.implementation.jsapi20:xsltSAPIDistribution
> Task :org.jvoicexml.implementation.jsapi20:xsltSphinxFreeTTS SKIPPED
> Task :org.jvoicexml.implementation.jsapi20:xsltSphinxFreeTTSDistribution
> Task :org.jvoicexml.implementation.jsapi20:jar
> Task :org.jvoicexml.implementation.lightweightbml:compileJava UP-TO-DATE
> Task :org.jvoicexml.implementation.lightweightbml:processResources NO-SOURCE
> Task :org.jvoicexml.implementation.lightweightbml:classes UP-TO-DATE
> Task :org.jvoicexml.implementation.lightweightbml:copyReferencedLibraries UP-TO-DATE
> Task :org.jvoicexml.implementation.lightweightbml:xslt
> Task :org.jvoicexml.implementation.lightweightbml:xsltDistribution
> Task :org.jvoicexml.implementation.lightweightbml:jar
> Task :org.jvoicexml.implementation.mrcpv2:compileJava UP-TO-DATE
> Task :org.jvoicexml.implementation.mrcpv2:processResources NO-SOURCE
> Task :org.jvoicexml.implementation.mrcpv2:classes UP-TO-DATE
> Task :org.jvoicexml.implementation.mrcpv2:copyReferencedLibraries
> Task :org.jvoicexml.implementation.mrcpv2:xsltImplementation
> Task :org.jvoicexml.implementation.mrcpv2:xsltImplementationDistribution
> Task :org.jvoicexml.implementation.mrcpv2:jar
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:compileJava UP-TO-DATE
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:processResources NO-SOURCE
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:classes UP-TO-DATE
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:copyReferencedLibraries UP-TO-DATE
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:xslt
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:xsltDistribution
> Task :org.jvoicexml.interpreter.datamodel.ecmascript:jar
> Task :org.jvoicexml.interpreter.grammar.regex:compileJava UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.regex:processResources UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.regex:classes UP-TO-DATE
> Task :org.jvoicexml.interpreter.grammar.regex:xslt
> Task :org.jvoicexml.interpreter.grammar.regex:xsltDistribution
> Task :org.jvoicexml.interpreter.grammar.regex:jar
> Task :org.jvoicexml.jndi:compileJava UP-TO-DATE
> Task :org.jvoicexml.jndi:processResources NO-SOURCE
> Task :org.jvoicexml.jndi:classes UP-TO-DATE
> Task :org.jvoicexml.jndi:copyReferencedLibraries
> Task :org.jvoicexml.jndi:xslt
> Task :org.jvoicexml.jndi:xsltDistribution
> Task :org.jvoicexml.jndi:jar
> Task :org.jvoicexml.talkinghead:compileJava UP-TO-DATE
> Task :org.jvoicexml.talkinghead:processResources UP-TO-DATE
> Task :org.jvoicexml.talkinghead:classes UP-TO-DATE
> Task :org.jvoicexml.talkinghead:copyReferencedLibraries UP-TO-DATE
> Task :org.jvoicexml.talkinghead:jar
> Task :org.jvoicexml.voicexmlunit:compileJava UP-TO-DATE
> Task :org.jvoicexml.voicexmlunit:processResources NO-SOURCE
> Task :org.jvoicexml.voicexmlunit:classes UP-TO-DATE
> Task :org.jvoicexml.voicexmlunit:jar
> Task :org.jvoicexml.voicexmlunit.demo:compileJava NO-SOURCE
> Task :org.jvoicexml.voicexmlunit.demo:processResources NO-SOURCE
> Task :org.jvoicexml.voicexmlunit.demo:classes UP-TO-DATE
> Task :org.jvoicexml.voicexmlunit.demo:jar
> Task :main:distTar
> Task :main:distZip
> Task :main:assemble
> Task :main:build

BUILD SUCCESSFUL in 59s

**Comment by schnelle** [comment]
The Mary implementation platform was indeed missed from the build. I merged a patch to develop. Could you please check if this issue is resolved?

**Comment by roberto-cisternino** [comment]
Yes it is solved in the last build ! Thanks.

**Comment by roberto-cisternino** [comment]
I close the issue as per my previous comment.
