### ISSUE TITLE
Gradle 3.0 Giving Errors

### ISSUE THREAD

**Issue by enanas** [JVoiceXML/JVoiceXML#161]
Hi Mr. Dirk and everyone!

When I first downloaded the project and tried to build it I got the following error and wanted to share and ask if it is a bug or not:

"Unable to find method 'org.gradle.api.invocation.Gradle.getIncludedBuilds()Ljava/util/Collection;'
org.gradle.api.invocation.Gradle.getIncludedBuilds()Ljava/util/Collection;

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes."

Steps to reproduce the error:

1. Download the version 0.7.8 release of the project.
2. Open it in an IDE. (I am using Intellij IDEA)
3. Try to build it. (The gradle-wrapper inside the project is 3.0.)
4. Get the error.

Things I have tried that didn't work:

1. Re-downloading the dependencies.
2. Stopping the gradle process.
3. Killing all java processes and restarting the gradle process.
4. Deleting the .gradle file and re-downloading the dependencies.

I know it is not elegant but the thing that worked:

1. Changing the gradle-wrapper's version to 5.0 or 5.4.6.
2. Deleting objecttagdemo project. (It uses toURL() in the parameters part of xslt in the build.gradle file but I couldn't find a replacement function to use in 5.4.6.)
3. Deleting the kinect project. (It is giving another error about msbuild, I will not be using the implementation platform parts of the project so this part is non-essential for me. For the people that will be using it unfortunately this solution is not feasible.)
4. It builds the project with 4 exceptions regarding the lack of providers on: https://repo.maven.apache.org/maven2/org/jvoicexml/ when it tries to access to https://repo.maven.apache.org/maven2/org/jvoicexml/org.jvoicexml.implementation.jtapi/0.7.8/ and https://repo.maven.apache.org/maven2/org/jvoicexml/org.jvoicexml.mmi.events/0.7.8/ .
5. The project is built.

Thanks!

**Comment by schnelle** [comment]
Gradle support in 0.7.8 was very limited. Still it is not good, but significantly improved in the current development branch.
Hence, I suggest to switch to the current development branch.

I am attaching a first draft of an improved how to build guide, which is currently work in progress with issue #140 .
[jvxml-howtobuild-0.7.9-SNAPSHOT.pdf](https://github.com/JVoiceXML/JVoiceXML/files/12488233/jvxml-howtobuild-0.7.9-SNAPSHOT.pdf)

**Comment by enanas** [comment]
I cloned the development branch and it builds without a problem. I will use this branch, thanks!
