### ISSUE TITLE
Reduce checkstyle issues before 0.7.9 release

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#167]

**Comment by rapgro** [comment]
SCNR https://miro.medium.com/v2/resize:fit:1024/1*-6Chq5Y5MCsqX4-Y5pz4pg.jpeg

**Comment by rapgro** [comment]
Well, release 0.7.8 is very old from 2018. Any plans when 0.7.9 is declared as stable?

**Comment by schnelle** [comment]
See the open issues which are planned to be fixed before a new release
https://github.com/JVoiceXML/JVoiceXML/milestone/2

**Comment by rapgro** [comment]
OK, so let's wait for final completion of documentation.
