### ISSUE TITLE
Disconnect tag in subdialogs

### ISSUE THREAD

**Issue by FlorianRas** [JVoiceXML/JVoiceXML#179]
It seems that disconnect in subdialogs does not close every contexts ( the call does not hangup after disconnect). In these vxml files, the sentence "After HangUp" is still prompted. 

[hangUpTest.txt](https://github.com/user-attachments/files/15984219/hangUpTest.txt)
[hangupTest2.txt](https://github.com/user-attachments/files/15984220/hangupTest2.txt)
[JVOICEHangupLOG.txt](https://github.com/user-attachments/files/15984255/JVOICEHangupLOG.txt)

**Comment by schnelle** [comment]
Verified and confirmed to be working
