### ISSUE TITLE
import org.jvoicexml.SpeakablePlainText not found

### ISSUE THREAD

**Issue by mainakanyi** [JVoiceXML/JVoiceXML#20]
import org.jvoicexml.SpeakablePlainText not found when I am trying to run the android application.

Best Regards

**Comment by schnelle** [comment]
what are you trying exactly?

**Comment by mainakanyi** [comment]
I am trying to call my VXML in Android. I am trying a sample code in this link but it isn't working. Please assist. https://github.com/spinifu/pfc/tree/master/workspace

**Comment by schnelle** [comment]
Did you consider contacting the author of that project directly? Unfortunatley, I was not aware of that.

**Comment by mainakanyi** [comment]
Thank you Schnelle.
I will try to contact the author.

**Comment by schnelle** [comment]
Great. I just discovered that the author was one of the students working on that issue. Unfortunatley, I lost contact. I think that I shoudl have a look at it, too.

**Comment by mainakanyi** [comment]
Thank you Schnelle. Please have a look at it. Looking forward to hearing from you.

Best Regards

**Comment by mainakanyi** [comment]
@schnelle How do I run this recorddemo. I am trying to run it in eclipse but I can't get any result except 

log4j:WARN No appenders could be found for logger (org.jvoicexml.demo.recorddemo.RecordDemo).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Please help

**Comment by schnelle** [comment]
Does this still occur after the switch to Gradle?
