### ISSUE TITLE
SRGS SISR JavaScript strings must be escaped before evaluation

### ISSUE THREAD

**Issue by michaelplevy** [JVoiceXML/JVoiceXML#23]
in sisr/AddToMatchedText.java and sisr/Context.java javascript strings are built to be executed. For instance, in Context.java in the method updateParentScope(), a string is built for javascript evaluation like:

```
        context.evaluateString(parentScope, "meta." + ruleName
                + "=function() {return {text:'" + ruleMetaCurrent
                + "', score:1.0}};", "Context:rule set meta." + ruleName, 0,
                null);
```
                
It is possible and legal for an utterance to have single quote (apostrope - ') characters in them. Some speech recognizers return strings with these characters. For example:

>   IVR: "Can I help you with something else?"
>   Caller: "i'm all set"

Since utterance strings may have single quotes, all generated SISR javascript strings must be properly escaped before evaluation. Otherwise, Javascript execution will fail with syntax errors like:

`  closeorg.mozilla.javascript.EvaluatorException: missing } after property list`

See escapeEcmaScript(String input) - https://commons.apache.org/proper/commons-lang/javadocs/api-3.4/org/apache/commons/lang3/StringEscapeUtils.html#escapeEcmaScript(java.lang.String)

Given the limited domain of strings returned in uterances, it may be sufficient to do a simple 
`  .replace("'", "\\'") `
to fix up these strings. I'm not sure.

**Comment by schnelle** [comment]
Sounds good. However, My preferred solution would be to employ a datamodel as it is already done for the VoiceXML parts to the SRGS processor. Here, all these cases are already handled. Moreover, it would pave the way for other scripting languages, e.g. Lua or what have you.

What do you think?

**Comment by schnelle** [comment]
I just pushed a version with your suggested fix. Adding support for the datamodel may be to timeconsuming.

**Comment by michaelplevy** [comment]
I don't have a preference for the solution. I tend towards simple and practical, even though it may not always be the "right" approach. Did you have a test case? I meant to post an example grammar.

**Comment by schnelle** [comment]
Sorry, but I cannot spot it. Could you hint me on that?

Actually, we may want to use the system test to utilize the W3C test suite for SRGS grammars to work more systematically on that. They are part of the system test and are waiting to be used.
