### ISSUE TITLE
system does not initiate hangup when using mrcpv2 platform

### ISSUE THREAD

**Issue by langep** [JVoiceXML/JVoiceXML#24]
When the VXML application reaches an </exit> the JVoiceXmlSession closes which also close the JVoiceXmlImplementationPlatform. However, I think that this should also invoke org.jvoicexml.mrcpv2.callmanager.SipCallManager.cleanupSession(). Currently, it is only called when the user initiates a hangup and not when the VXML application reaches an ending point. This causes the sip call to stay active until the user hangs up. 

Is there a way to propagate this information to the SipCallManager? Can I register maybe register it as a listener somewhere?

**Comment by schnelle** [comment]
The SipCallManager is already registered as a SessionListener. SipCallManager.cleanupSession() is also called in this method.

This is also called in JVoiceXmlSession.cleanup() when the session is called. Can you spot the corresponding logs?

**Comment by langep** [comment]
I could find it in the code. I have added a log message into SipCallManager.sessionEnded and SipCallManager.cleanupSession but sessionEnded does not seem to be called.

**Comment by schnelle** [comment]
A piece of your logging output might help to understand what's going on. Could you provide me with that as well as where you added your audition?

**Comment by langep** [comment]
```
    public void sessionEnded(final Session session) {
        String id = session.getSessionID();
        //workaround to deal with two id's
        //maps the voicexml sessionid to sip session id
        //needed for case when the voicxml session ends before a hang up and
        // need to get to close the sip session

        // get the sip sesison id

        //remove the session id mapping
        final String sipId;
        synchronized (ids) {
            sipId = ids.get(id);
            ids.remove(id);
        }

        //clean up the session
        cleanupSession(sipId);
        LOGGER.info("SipCallManager.sessionEnded was called");
[jvoicexml.log](https://github.com/JVoiceXML/JVoiceXML/files/1377766/jvoicexml.log)

    }
```

I have also moved around some things to see if that mattered but it seems this function is not called.
```
    private void cleanupSession(final String id) {

        final SipCallManagerSession session = sessions.get(id);
        if (session == null) {
            LOGGER.error("no session given. unable to cleanup session");
            return;
        }

        LOGGER.info("SipCallManager.cleanupSession was called");
        try {
            final SpeechClient client = session.getSpeechClient();
            client.stopActiveRecognitionRequests();
            client.shutdown();
            //need to check for null mrcp session (in speechcloud case it
            //will be null)
            final SipSession mrcpsession = session.getMrcpSession();
            if (mrcpsession != null) {
                mrcpsession.bye();
            }
            final SipSession pbxsession = session.getPbxSession();
            pbxsession.bye();
            LOGGER.info("SipCallManager.cleanupSession pbxsession.bye() was called");
        } catch (MrcpInvocationException e) {
            LOGGER.error(e.getMessage(), e);
        } catch (IOException e) {
            LOGGER.error(e.getMessage(), e);
        } catch (InterruptedException e) {
            LOGGER.error(e.getMessage(), e);
        } catch (NoMediaControlChannelException e) {
            LOGGER.error(e.getMessage(), e);
        } catch (SipException e) {
            LOGGER.error(e.getMessage(), e);
        }

        session.getJvxmlSession().hangup();
        //TODO Clean up after telephony client?
        //session.getTelephonyClient();

        //remove the session from the map
        sessions.remove(id);
    }
```

**Comment by langep** [comment]
Any idea why this is happening?

**Comment by langep** [comment]
I think this might be caused because there are sips systems. I saw JVXML open a server on port 4xxx but that is not actually the port that HALEF is using. We are using 50xx and I think the functionality is supplied by some 3rd party dependency. Maybe this is why the hangup is never triggered.

**Comment by schnelle** [comment]
In the meantime, SIP logging has also been made available in the JVoiceXML logs (part of the current develop branch).
We may need to reproduce and investigate the SIP logging on Cairo and JVoiceXML.

**Comment by schnelle** [comment]
The main reason seems to be that some errors happen outside JVoiceXML and JVoiceXML has no means to clean this up.
I will add this.

Additionally, the MRCP implementation platform does not make proper use of the external resources. It should use the Telephony interface but it doesn't. Acutally, it uses DesktopTelephony which does not make sense at all but it does not harm. I discivered that this was not possible as the telephony was not accessible to the call managers. I will also change this.
