### ISSUE TITLE
URL parameters not escaped correctly

### ISSUE THREAD

**Issue by hotblac** [JVoiceXML/JVoiceXML#27]
I'm attempting to access a vxml resource with URL parameters using Session.call(URI). Resource URL is http://localhost:9090/voicexmlriot-junit-demo/dynamicPage.jsp?param1=blah%2Bblah&param2=foo%2Bbar
where %2B is the URL encoding for plus (+).

The URL parameters are received correctly by JVoiceXmlDocumentServer with the %2B URL encoding but are then decoded while processing so that HttpSchemeStrategy requests URL http://localhost:9090/voicexmlriot-junit-demo/dynamicPage.jsp?param1=blah+blah&param2=foo+bar.
This fails, as + is then URL decoded as a space.

I think this problem is specific to the plus (+) character as plus (+) is itself the URL encoding for space. This means that if you URL decode it then encode it again, you get %20 (encoding for space) and not the plus (+) literal. For this reason, double-encoding the plus (+) in the URL does not work. This makes it impossible to request a URL with a + in it.

I think the problem is something to do with HttpSchemeStrategy.getInputStream(), around line 140. It builds the fragmentLessUri from the uri method parameter. As the URI class does URL encoding for us, building a new URI in this way decodes the original URI string then encodes it again when creating the new fragmentLessUri object. This works for most inputs but will fail for the plus (+) symbol.

Test case for this bug in my VoiceXMLRiot project: https://github.com/hotblac/voicexmlriot/commit/a0589ed3314686f7b9951f2655b1ca0300a05d12
Note that the VoiecXMLRiot driver.get() method eventually delegates to JVoiceXML Session.call().

I'm confident that this issue is in JVoiceXML rather than my own code as the following logging appears to confirm:

2018-02-25 18:25:26,426 INFO  JVoiceXmlDocumentServer:232 - loading document with URI 'http://localhost:9090/voicexmlriot-junit-demo/dynamicPage.jsp?param1=blah%2Bblah&param2=foo%2Bbar...
2018-02-25 18:25:26,445 DEBUG HttpSchemeStrategy:160 - connecting to 'http://localhost:9090/voicexmlriot-junit-demo/dynamicPage.jsp?param1=blah+blah&param2=foo+bar'...

JVoiceXmlDocumentServer shows the parameters correctly encoded. HttpSchemeStrategy shows the + symbol has been decoded.

**Comment by hotblac** [comment]
For debugging:
Actual values passed into HttpSchemeStrategy.getInputStream():
uri (toString()):  http://localhost:9090/voicexmlriot-junit-demo/dynamicPage.jsp?param1=blah%2Bblah&param2=foo%2Bbar
parameters: ArrayList size 0

In the problem case, parameters are passed in the uri string, not the parameters collection

**Comment by hotblac** [comment]
Fixed in pull request #32

**Comment by schnelle** [comment]
Thanks a lot. Merged.
