### ISSUE TITLE
Use a <var> tag and then <submit> within the namelist

### ISSUE THREAD

**Issue by thorty** [JVoiceXML/JVoiceXML#28]
Hello,

first: Great work. Thank you for this!
I will build a testing framework for my vxml application with JvoiceXML.

Here is a code snippet of my VXML:

```xml
<form>
 <block>
  <var name="ANI" expr="'1234567'"/>
  <submit next="/MyApp/ParseUserData" method="post" namelist="ANI"/>
 </block>
</form>
</vxml> 
```

My Problem when starting a call(session): 

`org.jvoicexml.event.error.SemanticError: error.semantic: 'ANI' not found`

It does not matter where I define the  ```<var>```. (Inside or outside <block>)

Is this a Issue? 
Would be great If you could help me.

Thanks!
Thorty

**Comment by hotblac** [comment]
A possible workaround for this is to declare your var inside a <script> tag rather than a <var>.

For example, [this](https://github.com/hotblac/voicexmlriot/blob/master/voicexmlriot-driver/src/test/resources/audio.vxml) parses fine in JVoiceXML 0.7.7.

It's not a fix for the issue but it may help till a fix is available.

**Comment by rapgro** [comment]
> If it occurs in executable content, it declares a variable in the anonymous scope associated with the enclosing <block>, <filled>, or catch element. 

https://www.w3.org/TR/voicexml20/#dml5.3.1

Can you provide an unit test maybe to have a showcase for the issue?

**Comment by schnelle** [comment]
Hey there,

I tried to reproduce the error without success. Also, the log shows that it is executed as expected (using the current master)

```
1397195 [75-b137-8e8c253f4f26] INFO  nterpreter.scope.ScopeObserver (    75) [] entering new scope 'anonymous'...
1397196 [75-b137-8e8c253f4f26] DEBUG nterpreter.scope.ScopeObserver (    80) [] current scope stack: [SESSION, APPLICATION, DOCUMENT, DIALOG, ANONYMOUS]
1397196 [75-b137-8e8c253f4f26] DEBUG ecmascript.EcmaScriptDataModel (   135) [] created scope 'ANONYMOUS'
1397196 [75-b137-8e8c253f4f26] DEBUG ecmascript.EcmaScriptDataModel (   710) [] set 'F16340a8bfadS000003' to 'true'
1397197 [75-b137-8e8c253f4f26] DEBUG rpreter.formitem.BlockFormItem (    92) [] block 'F16340a8bfadS000003' marked as visited.
1397197 [75-b137-8e8c253f4f26] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
1397379 [75-b137-8e8c253f4f26] DEBUG ecmascript.EcmaScriptDataModel (   929) [] evaluated ''1234567';' to '1234567'
1397379 [75-b137-8e8c253f4f26] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'ANI' expr: '1234567'
1397380 [75-b137-8e8c253f4f26] DEBUG ecmascript.EcmaScriptDataModel (   370) [] created 'ANI' with '1234567'
1397380 [75-b137-8e8c253f4f26] INFO  vxml21.tagstrategy.VarStrategy (   147) [] created var name 'ANI': '1234567'
1397381 [75-b137-8e8c253f4f26] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
1397382 [75-b137-8e8c253f4f26] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'submit' next: '/MyApp/ParseUserData' method: 'post' namelist: 'ANI'
1397383 [75-b137-8e8c253f4f26] DEBUG l21.tagstrategy.SubmitStrategy (   134) [] submitting to uri '/MyApp/ParseUserData'...
1397391 [75-b137-8e8c253f4f26] INFO  nterpreter.scope.ScopeObserver (   100) [] exiting scope 'anonymous'...
```

Could you please check again?

**Comment by schnelle** [comment]
No response and is working for me.
