### ISSUE TITLE
Build fails due to missing org_jvoicexml_implementation_kinect_KinectRecognizer.h

### ISSUE THREAD

**Issue by hotblac** [JVoiceXML/JVoiceXML#29]
On first build using `gradle build` or `gradlew build`, the build fails with error:

```
:org.jvoicexml.implementation.kinect:buildJniWin32
  KinectRecognizer.cpp
KinectRecognizer.cpp(24): fatal error C1083: Cannot open include file: 'org_jvoicexml_implementation_kinect_KinectRecognizer.h': No such file or directory [C:\dev\projects\JVoiceXML\org.jvoicexml.implementation.kinect\src\main\cpp\JVoiceXmlKinectRecognizer.vcxproj]
:org.jvoicexml.implementation.kinect:buildJniWin32 FAILED
```

The required file is created by an earlier build step and written to org.jvoicexml.implementation.kinect\build\include directory. However, it is not available when attempting to build the KinectRecognizer.cpp.

A workaround is to copy the `org_jvoicexml_implementation_kinect_KinectRecognizer.h` file to org.jvoicexml.implementation.kinect\src\main\cpp and rerun the build.

To resolve, the build.gradle for this component should be corrected to make the required header file available to the `buildJniWin32` and `buildJniWin64` build steps.

**Comment by schnelle** [comment]
I corrected the project setup of the C++ project to account for the modified location of the generated header files.
