### ISSUE TITLE
Broken org.jvoicexml tests

### ISSUE THREAD

**Issue by hotblac** [JVoiceXML/JVoiceXML#30]
On running a standard `gradle build`, the build fails at task `:org.jvoicexml:test` with test failures. The generated test report shows 62 of 190 tests failing.

Tests should be corrected or removed / disabled to enable the build to complete successfully.

Test results attached.
[test.zip](https://github.com/JVoiceXML/JVoiceXML/files/1799429/test.zip)

**Comment by hotblac** [comment]
Can this please be assigned to me? I've started work in https://github.com/hotblac/JVoiceXML/tree/feature/test-fixes

**Comment by hotblac** [comment]
Resolved by Pull request #31

**Comment by schnelle** [comment]
Thanks a lot. Merged.
