### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by Mayzz03** [JVoiceXML/JVoiceXML#34]
After many days of searching for no results trying to find a way to make VXML work on Asterisk I gave up.

I just discovered JVoiceXML. However I can not find any documentation, no instructions on how it works. Does it support SIP lines ??? How are incoming and outgoing calls going?

Is JVoiceXML just a VXML interpreter or an IVR too?

Thank you for your reply.

**Comment by schnelle** [comment]
Adding to Patrick's good response:
The recommended way to start would be to clone the master branch and start with the mrcp platform as already mentioned. We may certainly help if any issues pop up to have this resolved.

Maybe, this could also become a starting point to improve the existing documentation in this regard.

**Comment by schnelle** [comment]
No response from OP, so assuming that all questions have been resolved.

**Comment by fatdunky** [comment]
I found the following documents very helpful. Even though they are massively out of date. 

http://download2.polytechnic.edu.na/pub4/sourceforge/j/jv/jvoicexml/howtobuild/1.9.9/jvxml-howtobuild-1.9.9.pdf

http://download2.nust.na/pub4/sourceforge/j/project/jv/jvoicexml/userguide/0.7.6.GA/jvxml-userguide-0.7.6.GA.pdf

I'm also trying to get JVoicexml going with Asterix (and a Unimrcp ASR via mrcpv2). My current under standing is, you need to code up your jvoicexml client to use something like this  http://asterisk-java.org/.  I'll let you know how i go.

**Comment by rapgro** [comment]
Sourceforge is nearly dead. We therefore recommend and decided to move to GitHub. Obviously, some information got lost.
```
<rant>
As GitHub was recently bought by Microsoft and actually it's not clear what it will mean for FLOSS projects, should we move again? Maybe some Gitlab is the future, also for the JVoiceXML project. Though, if you look deeper into details, then you can see gitlab.com is obviously hosted by Microsoft Azure, so we won't gain much. Offtopic, maybe open a new ticket for this recommendation?
https://news.microsoft.com/2018/06/04/microsoft-to-acquire-github-for-7-5-billion/
https://about.gitlab.com/2016/07/13/how-to-setup-a-gitlab-instance-on-microsoft-azure/
</rant>
```

**Comment by rapgro** [comment]
Did you consolidate?
https://github.com/JVoiceXML/JVoiceXML/tree/master/org.jvoicexml/doc
https://github.com/JVoiceXML/JVoiceXML/tree/master/userguide

**Comment by fatdunky** [comment]
Ah there it is:

So i was able to build the userguide after downloading https://miktex.org/.

Then running gradle -Pversion=0.7.8-SNAPSHOT 

The build failed, but the PDF was under .gradle/latex-tmp

**Comment by rapgro** [comment]
Addon to my rant abobe:
“Google as a public cloud, they have more experience than the other public cloud providers because they basically made a cloud for themselves,” he [CEO Sid Sijbrandij] said in an interview with VentureBeat.
https://venturebeat.com/2018/04/06/why-and-how-gitlab-abandoned-microsoft-azure-for-google-cloud/
https://about.gitlab.com/2018/06/25/moving-to-gcp/
https://about.gitlab.com/google-cloud-platform/
