### ISSUE TITLE
issue with jvoicexml version 0.7.8

### ISSUE THREAD

**Issue by annieann91** [JVoiceXML/JVoiceXML#35]
Hi, I have a problem in my server jvoice xml ,
here it is my client_code:

import java.net.URI;

import java.net.URISyntaxException;
import java.net.URL;
import java.util.Hashtable;

import java.rmi.Remote;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;

import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NameClassPair;
import javax.naming.NamingEnumeration;
import javax.naming.NamingException;

import org.jvoicexml.ConnectionInformation;
import org.jvoicexml.JVoiceXml;
import org.jvoicexml.Session;
import org.jvoicexml.client.BasicConnectionInformation;
import org.jvoicexml.event.ErrorEvent; // JVoiceXML Imports from User Library

class Policy {
	@SuppressWarnings("unused")
	ClassLoader cl = null;
	@SuppressWarnings("unused")
	URL policyURL = null;

	Policy() {
		final ClassLoader cl = getClass().getClassLoader();
		final URL policyURL = cl.getResource("policy/jvoicexml.policy");
		System.err.println("policyURL = " + policyURL);
		// this policy file must be created in this case in the config folder
		System.setProperty("java.security.policy", policyURL.toString());
	}
}

public class JVoiceXML_Client {

	public static void main(final String[] args) {

		final Policy p = new Policy();
		Context context = null;
		final Hashtable<Object, Object> env = new Hashtable<>();
		env.put("java.naming.factory.initial", "com.sun.jndi.rmi.registry.RegistryContextFactory");
		env.put("java.naming.provider.url", "rmi://localhost:1099");
		env.put("java.naming.rmi.security.manager", "true");
		try {
			context = new InitialContext(env);
			final NamingEnumeration<NameClassPair> list = context.list("");
			while (list.hasMore()) {
				System.out.println(list.next().getName());
			}
		} catch (final NamingException e) {
			e.printStackTrace();
			System.exit(-1);
		}
		JVoiceXml jvxml = null;
		try {
			jvxml = (JVoiceXml) context.lookup("JVoiceXml");
			final ConnectionInformation info = new BasicConnectionInformation("dummy", "jsapi10", "jsapi10");
			final Session session = jvxml.createSession(info);

			final URI uri = new URI("file:///C://Users//A693819//eclipse-workspace//test//helloword.vxml");
			session.call(uri);
			session.waitSessionEnd();
			session.hangup();
		} catch (final NamingException e) {
			e.printStackTrace();
			System.exit(-1);
		} catch (final ErrorEvent e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (final URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}

and here is the error that I get in the client side : 

policyURL = file:/C:/Users/A693819/eclipse-workspace/test/bin/policy/jvoicexml.policy
Session.f9862a32-cbe1-456d-9ab9-179f77cd65d3
Application.daed8b56-d4ad-41a0-a326-9ade874037e8
Session.593e3d68-6512-4497-840e-ce629e966b7e
RemoteJVoiceXml
Application.0e458245-5f39-4bb6-ac24-a33e53fe679c
RemoteApplication.caea841a-d85e-471b-9bb3-4d8b2da54449
RemoteMappedDocumentRepository
RemoteSession.caea841a-d85e-471b-9bb3-4d8b2da54449
Session.57ff5f52-2f7b-40fa-b66e-21bbe8949c88
MappedDocumentRepository
RemoteApplication.593e3d68-6512-4497-840e-ce629e966b7e
RemoteSession.daed8b56-d4ad-41a0-a326-9ade874037e8
RemoteSession.f9862a32-cbe1-456d-9ab9-179f77cd65d3
Session.1f6a91b9-617f-479a-afd7-d5f7477199d0
Application.caea841a-d85e-471b-9bb3-4d8b2da54449
RemoteSession.0e458245-5f39-4bb6-ac24-a33e53fe679c
Session.9dc6112f-e9fb-44cf-8a20-4d9bca0e3186
Application.f9862a32-cbe1-456d-9ab9-179f77cd65d3
Application.593e3d68-6512-4497-840e-ce629e966b7e
RemoteApplication.57ff5f52-2f7b-40fa-b66e-21bbe8949c88
JVoiceXml
RemoteApplication.1f6a91b9-617f-479a-afd7-d5f7477199d0
Application.57ff5f52-2f7b-40fa-b66e-21bbe8949c88
RemoteSession.593e3d68-6512-4497-840e-ce629e966b7e
Session.daed8b56-d4ad-41a0-a326-9ade874037e8
Session.0e458245-5f39-4bb6-ac24-a33e53fe679c
RemoteSession.57ff5f52-2f7b-40fa-b66e-21bbe8949c88
RemoteSession.1f6a91b9-617f-479a-afd7-d5f7477199d0
RemoteApplication.daed8b56-d4ad-41a0-a326-9ade874037e8
RemoteApplication.f9862a32-cbe1-456d-9ab9-179f77cd65d3
RemoteSession.9dc6112f-e9fb-44cf-8a20-4d9bca0e3186
Session.caea841a-d85e-471b-9bb3-4d8b2da54449
RemoteApplication.0e458245-5f39-4bb6-ac24-a33e53fe679c
Application.1f6a91b9-617f-479a-afd7-d5f7477199d0
org.jvoicexml.event.error.NoresourceError: error.noresource: Pool of type 'dummy' is unknown!
	at org.jvoicexml.implementation.pool.KeyedResourcePool.borrowObject(KeyedResourcePool.java:106)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.getExternalResourceFromPool(JVoiceXmlImplementationPlatform.java:710)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.getCallControl(JVoiceXmlImplementationPlatform.java:479)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlPromptAccumulator.renderPrompts(JVoiceXmlPromptAccumulator.java:119)
	at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.renderPrompts(JVoiceXmlImplementationPlatform.java:1055)

	at org.jvoicexml.profile.vxml21.tagstrategy.TextStrategy.execute(TextStrategy.java:121)
	at org.jvoicexml.profile.TagStrategyExecutor.executeTagStrategy(TagStrategyExecutor.java:206)
	at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:178)
	at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:82)
	at 

org.jvoicexml.interpreter.FormInterpretationAlgorithm.visitBlockFormItem(FormInterpretationAlgorithm.java:1164)
	at org.jvoicexml.interpreter.formitem.BlockFormItem.accept(BlockFormItem.java:107)
	at org.jvoicexml.interpreter.FormInterpretationAlgorithm.collect(FormInterpretationAlgorithm.java:639)
	at 
org.jvoicexml.interpreter.FormInterpretationAlgorithm.mainLoop(FormInterpretationAlgorithm.java:421)
	at org.jvoicexml.interpreter.VoiceXmlInterpreter.process(VoiceXmlInterpreter.java:258)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:817)
	at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:543)
	at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:396)

my jvoice_xml implementation file is this:

<?xml version="1.0" encoding="UTF-8"?>
<implementation xmlns:beans="[url]http://www.springframework.org/schema/beans"
  xmlns:xsi="[url]http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="jvxml-implementation-0-7.xsd">
  <beans:bean
    class="org.jvoicexml.implementation.jvxml.DummyTelephonySupportFactory">
    <beans:property name="instances" value="1" />
  </beans:bean>
</implementation>

and on the server side the error is this:

1367907 [ion(37)-192.168.56.1] ERROR jvoicexml.jndi.SessionSkeleton (   171) [] error.noresource: Pool of type 'dummy' is unknown!
org.jvoicexml.event.error.NoresourceError: error.noresource: Pool of type 'dummy' is unknown!
        at org.jvoicexml.implementation.pool.KeyedResourcePool.borrowObject(KeyedResourcePool.java:106) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.getExternalResourceFromPool(JVoiceXmlImplementationPlatform.java:710) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.getCallControl(JVoiceXmlImplementationPlatform.java:479) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.implementation.jvxml.JVoiceXmlPromptAccumulator.renderPrompts(JVoiceXmlPromptAccumulator.java:119) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.implementation.jvxml.JVoiceXmlImplementationPlatform.renderPrompts(JVoiceXmlImplementationPlatform.java:1055) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.profile.vxml21.tagstrategy.TextStrategy.execute(TextStrategy.java:121) ~[?:?]
        at org.jvoicexml.profile.TagStrategyExecutor.executeTagStrategy(TagStrategyExecutor.java:206) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:178) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.profile.TagStrategyExecutor.executeChildNodes(TagStrategyExecutor.java:82) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.FormInterpretationAlgorithm.visitBlockFormItem(FormInterpretationAlgorithm.java:1164) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.formitem.BlockFormItem.accept(BlockFormItem.java:107) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.FormInterpretationAlgorithm.collect(FormInterpretationAlgorithm.java:639) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.FormInterpretationAlgorithm.mainLoop(FormInterpretationAlgorithm.java:421) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.VoiceXmlInterpreter.process(VoiceXmlInterpreter.java:258) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.interpret(VoiceXmlInterpreterContext.java:817) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.VoiceXmlInterpreterContext.process(VoiceXmlInterpreterContext.java:543) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]
        at org.jvoicexml.interpreter.JVoiceXmlSession.run(JVoiceXmlSession.java:396) ~[org.jvoicexml-0.7.8-SNAPSHOT.jar:0.7.8-SNAPSHOT]

Anne

**Comment by annieann91** [comment]
thank you it works ,

but I have another problem this time ,when I launch this time the client program using a local uri that I run on my tomact server:
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'script'
792436 [Thread-253          ] DEBUG l21.tagstrategy.ScriptStrategy (   188) [] evaluating internal script: // verifie si la variable passee en parametre est definie ou non
                function defined(variable)
                {
                        if (typeof variable != 'undefined')
                        {
                                return true;
                        }
                        return false;

                }
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'property' name: 'termchar' value: ' '
792436 [Thread-253          ] INFO  1.tagstrategy.PropertyStrategy (    94) [] set property 'termchar' to value ' '
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'jsessionid' expr: ''89FC9F7AF666C8CEFE653266BAA9009B''
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'jsessionid' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_guide'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_guide' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_guide' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_guide' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_pause' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_pause' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_repeter' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_repeter' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_matricule' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_matricule' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_error' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_error' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_diffusion_error' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_diffusion_error' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_error_zep' expr: '2'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_error_zep' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'max_boucle_chgt_rptx' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'max_boucle_chgt_rptx' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_depeche_chgt_rptx' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_depeche_chgt_rptx' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'max_boucle_saisie_matricule_dtmf' expr: '2'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'max_boucle_saisie_matricule_dtmf' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_max_error_dtmf' expr: '3'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_max_error_dtmf' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_prompt'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_prompt' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_message'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_message' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_error_prompt'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_error_prompt' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_error_message'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_error_message' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_grammars'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_grammars' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_grammars_namelist'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_grammars_namelist' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_asr_class'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_asr_class' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_guide_off'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_guide_off' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_data_validation_action'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_data_validation_action' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_error_end_action'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_error_end_action' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'saisie_reprompt_initial_message'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'saisie_reprompt_initial_message' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'varDate'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'varDate' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'varPrompt'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'varPrompt' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'var' name: 'varPromptBargein'
792436 [Thread-253          ] DEBUG vxml21.tagstrategy.VarStrategy (   123) [] ignoring expr of name 'varPromptBargein' in a subdialog
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: 'property' name: 'com.genesyslab.dtmf.offboard_recognition' value: 'true'
792436 [Thread-253          ] INFO  1.tagstrategy.PropertyStrategy (    94) [] set property 'com.genesyslab.dtmf.offboard_recognition' to value 'true'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] INFO  ter.VoiceXmlInterpreterContext (   878) [] ...done initializing document
792436 [Thread-253          ] INFO  nterpreter.scope.ScopeObserver (    75) [] entering new scope 'dialog'...
792436 [Thread-253          ] DEBUG nterpreter.scope.ScopeObserver (    80) [] current scope stack: [DOCUMENT, DIALOG]
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   180) [] creating implicit variable for 'dialog'
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   135) [] created scope 'DIALOG'
792436 [Thread-253          ] DEBUG er.event.JVoiceXmlEventHandler (   184) [] found 0 catch elements in dialog 'D163726972eaS000069'
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   261) [] initializing FIA for dialog 'D163726972eaS000069' using profile 'VoiceXML21'...
792436 [Thread-253          ] DEBUG er.FormInterpretationAlgorithm (   324) [] initializing form item 'F163726972f4S00006c'
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   917) [] ignoring empty value expr
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   370) [] created 'F163726972f4S00006c' with 'null'
792436 [Thread-253          ] INFO  rpreter.formitem.BlockFormItem (   136) [] initialized block form item 'F163726972f4S00006c' with 'null'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   299) [] found 1 form items in dialog 'D163726972eaS000069'...
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   402) [] starting main loop for form 'D163726972eaS000069'...
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   556) [] selecting next form item in dialog 'D163726972eaS000069'...
792436 [Thread-253          ] DEBUG eter.formitem.AbstractFormItem (   179) [] checking if selectable
792436 [Thread-253          ] DEBUG eter.formitem.AbstractFormItem (   181) [] value of   'F163726972f4S00006c': 'null'
792436 [Thread-253          ] DEBUG eter.formitem.AbstractFormItem (   182) [] cond of    'F163726972f4S00006c': 'true'
792436 [Thread-253          ] DEBUG eter.formitem.AbstractFormItem (   183) [] selectable 'F163726972f4S00006c': true
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   413) [] next form item in form 'D163726972eaS000069' is 'F163726972f4S00006c'
792436 [Thread-253          ] INFO  nterpreter.VoiceXmlInterpreter (   125) [] entered state WAITING
792436 [Thread-253          ] INFO  er.FormInterpretationAlgorithm (   602) [] collecting 'F163726972f4S00006c'...
792436 [Thread-253          ] DEBUG er.FormInterpretationAlgorithm (  1153) [] visiting block 'F163726972f4S00006c'...
792436 [Thread-253          ] INFO  nterpreter.scope.ScopeObserver (    75) [] entering new scope 'anonymous'...
792436 [Thread-253          ] DEBUG nterpreter.scope.ScopeObserver (    80) [] current scope stack: [DOCUMENT, DIALOG, ANONYMOUS]
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   135) [] created scope 'ANONYMOUS'
792436 [Thread-253          ] DEBUG ecmascript.EcmaScriptDataModel (   710) [] set 'F163726972f4S00006c' to 'true'
792436 [Thread-253          ] DEBUG rpreter.formitem.BlockFormItem (    92) [] block 'F163726972f4S00006c' marked as visited.
792446 [Thread-253          ] DEBUG agstrategy.AbstractTagStrategy (   277) [] node: '#text'


jvoicexml is not taking into account the different var I don't understand where is the problem why it does not ?

**Comment by annieann91** [comment]
the problem is it does not interpret my subdialogs

**Comment by schnelle** [comment]
Could ypu please, paste a snippet of your VoiceXML and describe the desired behavior?

**Comment by schnelle** [comment]
Closed as there was no update.
