### ISSUE TITLE
Broken org.jvoicexml.config tests

### ISSUE THREAD

**Issue by hotblac** [JVoiceXML/JVoiceXML#38]
When I run gradle org.jvoicexml.config:build, the the build fails with test failures. All 6 tests in this project fail. 

Tests should be corrected or removed / disabled to enable the build to complete successfully.

Test results attached.
[test.zip](https://github.com/JVoiceXML/JVoiceXML/files/1983200/test.zip)

**Comment by hotblac** [comment]
Fixed in pull #39. Please review and close this issue.

**Comment by schnelle** [comment]
Thank you so much. Looks good
