### ISSUE TITLE
How to use with maven

### ISSUE THREAD

**Issue by NoMaillard** [JVoiceXML/JVoiceXML#41]
Hi,
I've successfully compiled JVoiceXML using gradle, but now i want to use it as a maven dependency, is this possible ? if so how can i do that ?

Thanks in advance

**Comment by schnelle** [comment]
This should be feasible if you call the install task in gradle. This will put the JVoiceXML jars into your local maven repository $HOME/.m2

From there on you should be able to consume them from your maven project.

**Comment by NoMaillard** [comment]
Awesome, thanks !
