### ISSUE TITLE
[subdialog] namelist is not added to HTTP query

### ISSUE THREAD

**Issue by NoMaillard** [JVoiceXML/JVoiceXML#44]
As per https://docs.microsoft.com/en-us/previous-versions/office/developer/speech-technologies/ff929007(v=msdn.10)

the namelist is never added to the URI requesting the subdialog

**Comment by schnelle** [comment]
Please, refer to the original specification and not a copy: https://www.w3.org/TR/voicexml20/#dml1.5.3

The specification does not state that the namelist should be handled via a URI mechanism. So, the actual implementation may also use other means.

I still have to check if the current implemtation works correctly.

**Comment by schnelle** [comment]
Agreed that fetching the document must include the variables from the namelist.

**Comment by rapgro** [comment]
> Please, refer to the original specification and not a copy: https://www.w3.org/TR/voicexml20/#dml1.5.3
Does Microsoft use its own implementation with additional special features? That wouldn't wonder because they do such things all way long in their projects forked from others.

**Comment by schnelle** [comment]
Raphael, please, see above.

**Comment by schnelle** [comment]
Incorrectly marked as resolved per #48

**Comment by schnelle** [comment]
Resolved.
