### ISSUE TITLE
[subdialog] reason to ignore var in a subdialog

### ISSUE THREAD

**Issue by NoMaillard** [JVoiceXML/JVoiceXML#45]
is there a specific reason the VarStrategy refuses to initialise vars in a subdialog ?
the VoiceXML spec seems to dictate otherwise

> The <subdialog> element invokes a 'called' dialog (known as the subdialog) identified by its src or srcexpr attribute in the 'calling' dialog. The subdialog executes in a new execution context that includes all the declarations and state information for the subdialog, the subdialog's document, and the subdialog's application root (if present), with counters reset, and **variables initialized**. The subdialog proceeds until the execution of a <return> or <exit> element, or until no form items remain eligible for the FIA to select (equivalent to an <exit>). A <return> element causes control and data to be returned to the calling dialog (Section 5.3.10). When the subdialog returns, its execution context is deleted, and execution resumes in the calling dialog with any appropriate <filled> elements.

**Comment by schnelle** [comment]
No, there is no specific reason. If the behaviour is not in line with the specification it is a bug.

**Comment by schnelle** [comment]
OK. Found the reason, which is obviously wrong. Evaluating the parameters passed to the dialog is done before the subdialog gets executed. This behavior needs to be changed.

**Comment by schnelle** [comment]
Fixed the behavior. Please, check again.
