### ISSUE TITLE
Grammar with fetchhint=safe are never downloaded

### ISSUE THREAD

**Issue by NoMaillard** [JVoiceXML/JVoiceXML#52]
it seems like grammars with the fetchhint attribute set to safe are never downloaded, there is no mechanism to download the grammar when we want to access it's data

**Comment by schnelle** [comment]
Disabled the intended use of a special reference grammar. Actually this one was returend but never loaded. As all documents are loaded when they are needed, this construct did not make much sense.

**Comment by schnelle** [comment]
Need to revisit this decision. Trying to rethink how this may be implemented in a better way.

**Comment by schnelle** [comment]
Introduce a new GrammarDocument to actually download the grammar in case the content is accessed.
