### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by royakash07** [JVoiceXML/JVoiceXML#55]
Please Update your documentation of the application as per the latest changes as it is difficult to identify the correct way to build project.
I don't about experts but for beginners.
Thanks

**Comment by schnelle** [comment]
This seems to be a checken and egg problem. The documentation has been updated but the changes have not been published yet. So you need to check the project ut and build at least the documentation to understand how it is supposed to be built.

**Comment by rapgro** [comment]
Well, we could ship a prebuilt (and fastly outdated) documentation besides the instructions how to manually rebuild a current one. I've seen such a solution in other projects to support different distributions that don't provide every needed dependencies for optional parts like automatic generation of documentation.

**Comment by schnelle** [comment]
The documentation had been updated with the last release and should be better, now.

No further actions here, despite the general aim to improve the documentation.
