### ISSUE TITLE
Android Callmanager project can‘t run。

### ISSUE THREAD

**Issue by mylater** [JVoiceXML/JVoiceXML#59]
Hi Schnelle,
I  can‘t execute Callmanager project on Android branch right way, is any sugesstion for me ?

Thanks!

**Comment by schnelle** [comment]
How do you try to run the project? The entry point for Android is in org.jvoicexml.client.android

Note, that this branch is not in sync with the current head and relies on the text platform for evaluation purpose, right now.

**Comment by schnelle** [comment]
As there ar no more questions or updates, I am closing this issue.
