### ISSUE TITLE
Setup a CI platform

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#60]

**Comment by rapgro** [comment]
You could look into Travis CI but it requires to keep with GitHub.
General discussion: https://www.informatik-aktuell.de/entwicklung/methoden/fuenf-gruende-um-mit-continuous-testing-zu-scheitern.html

**Comment by schnelle** [comment]
Thanks for the hint. I am aware that Travis relies on GitHub. So far, I just want to get started and this seems to be the easiest way to do so.

What other CI frameworks do you recommend with these capababilities and with a smooth setup as it is provided with Travis?

**Comment by schnelle** [comment]
Thanks for the hint. I am aware that Travis relies on GitHub. So far, I just want to get started and this seems to be the easiest way to do so.

What other CI frameworks do you recommend with these capababilities and with a smooth setup as it is provided with Travis?

**Comment by rapgro** [comment]
Well, it mostly depends on the goals to achieve. See given link above (german blog).
It's definitely not a simple and easy process to implement something and there's no out-of-the-box solution that applies perfectly and everywhere. Maybe for the java world, Jenkins is worth as a starting point, but it needs plugins for individual steps of the custom pipeline. First step, define a pipeline.

**Comment by schnelle** [comment]
Thanks. As there are no obvious issues against this way, I do not see a need for change to change the direction.
