### ISSUE TITLE
New idea: Use speech recognition to manage clusters and virtual machines

### ISSUE THREAD

**Issue by rapgro** [JVoiceXML/JVoiceXML#67]
Maybe doable with Python and ZeroMQ.
https://github.com/dnaeon/py-vpoller

Currently, I try to provide the needed stack in Fedora.

**Comment by rapgro** [comment]
https://i.emezeta.com/weblog/anecdotas-programacion/daemon-stop.png

**Comment by schnelle** [comment]
Thank you Raphael.

I think that this might be a use case that you could accomplish with JVoiceXML. However, this should be better handled in another project, maybe referring to this one. Therefore I am closing the issue as out of scope for this project.

**Comment by rapgro** [comment]
Hi Dirk,
thanks for your interest. No problem so far to close here.
It takes even more time e.g. to import all packages because of the bureaucracy hidden behind all the coding.
