### ISSUE TITLE
MatchConsumption execute javascript error

### ISSUE THREAD

**Issue by fjcondy** [JVoiceXML/JVoiceXML#70]
in org.jvoicexml.srgs.MatchConsumption  class: executeSisr method:
`context.evaluateString(
                workingScope,
                "var out=new Object();\nvar rules=new Object();\n"
                        + "var meta={current: function() {return {text:'', score:1.0}}};\n",
                "SISR init from MatchConsumer", 0, null);`

this eval script need add semicolon in the "return" statement. or else will throw error
`context.evaluateString(
                workingScope,
                "var out=new Object();\nvar rules=new Object();\n"
                        + "var meta={current: function() {return {text:'', score:1.0} ; }};\n",
                "SISR init from MatchConsumer", 0, null);`

**Comment by schnelle** [comment]
Fixed (+several other locations with the same cause).

Please, test again.
