### ISSUE TITLE
SrgsXmlOptionConverter need set default Grammer type

### ISSUE THREAD

**Issue by fjcondy** [JVoiceXML/JVoiceXML#71]
in class org.jvoicexml.interpreter.formitem.SrgsXmlOptionConverter ,createVoiceGrammar ,createDtmfGrammar method return Grammer object need set default grammer type or else maybe adapter to regexGrammar to execute.

> public Grammar createDtmfGrammar(final Collection<Option> options) {
        if ((options == null) || options.isEmpty()) {
            return null;
        }
        try {
            final SrgsXmlDocument document = new SrgsXmlDocument();
            final Grammar grammar = document.getGrammar();
            //modify by Condy 2019.02.14 grammar要设置一个默认的类型
            **grammar.setType(GrammarType.SRGS_XML);**
            final Rule rule = grammar.appendChild(Rule.class);
            final String name = getName(ModeType.DTMF);
            rule.setId(name);

> @Override
    public Grammar createVoiceGrammar(final Collection<Option> options,
            final Locale language) {
        if ((options == null) || options.isEmpty()) {
            return null;
        }
        try {
            final SrgsXmlDocument document = new SrgsXmlDocument();
            final Grammar grammar = document.getGrammar();
            //modify by Condy 2019.02.14 grammar要设置一个默认的类型
            **grammar.setType(GrammarType.SRGS_XML);**
            grammar.setXmlLang(language);
            final Rule rule = grammar.appendChild(Rule.class);
            final String name = getName(ModeType.VOICE);

**Comment by schnelle** [comment]
Please, provide more details why you think that this would be necessary.

**Comment by fjcondy** [comment]
when not set default granmmer type.  jvoice will try to identifer grammer type,and it maybe identiy wrong.
can see this issue:

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<vxml xmlns="http://www.w3.org/2001/vxml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	version="2.1" xml:lang="en"
	xsi:schematicLocation="http://www.w3.org/2001/vxml http://www.w3.org/TR/voicexml20/vxml.xsd">
	<meta content="JVoiceXML group" name="author" />
	<meta content="2005-2012 JVoiceXML group - http://jvoicexml.sourceforge.net"
		name="copyright" />
	<form id="order">
	     <block>
		    We need a few more details to complete your order.
		  </block>
	     <field name="color">
	        <property name="termchar" value="a" />
	        <property name="topic" value="yesno" />
		    <prompt>Which color?</prompt>
		    <option>red</option>
		    <option>blue</option>
		    <option>green</option>
		  </field>
		  <field name="size">
		    <prompt>Which size?</prompt>
		    <option>small</option>
		    <option>medium</option>
		    <option>large</option>
		  </field>
		  <field name="quantity">
		    <grammar type="application/srgs+xml" src="builtin:voice/digits?minlength=1;maxlength=2"/>
		    <prompt>How many?</prompt>
		    <nomatch count="1">
		      <prompt>Please say the number of items to be ordered.</prompt>
		    </nomatch>
		  </field>
	      <block>
	       <prompt>
		    Thank you.  Your order is being processed. color is:<value expr="color"/> and size is:<value expr="size" /> and quantity is:<value expr="quantity"/>
		    </prompt>
		  </block>
		  
		</form>
</vxml>`

grammer type was identifier  application/grammar+regex  in GrammarIdentifierCentral whern grammer not set default type.

>  22257 [TextSenderThread    ] DEBUG entation.text.TextSenderThread (   109) [] ... done sending output
 22257 [aa-b781-39b0861c2faf] DEBUG er.FormInterpretationAlgorithm (  1095) [] found 1 grammar node(s)
 22257 [TextSenderThread    ] DEBUG entation.text.TextSenderThread (    97) [] trying to take next message
 22259 [aa-b781-39b0861c2faf] DEBUG er.FormInterpretationAlgorithm (   913) [] preprocessing grammar <grammar xmlns="http://www.w3.org/2001/06/grammar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" root="OGVOICE168fb9d89c2S000001" version="1.0" xml:lang="en" xsi:schemaLocation="http://www.w3.org/2001/06/grammar http://www.w3.org/TR/speech-grammar/grammar.xsd"><rule id="OGVOICE168fb9d89c2S000001"><one-of><item>red</item><item>blue</item><item>green</item></one-of></rule></grammar>...
 22260 [aa-b781-39b0861c2faf] DEBUG nterpreter.VoiceXmlInterpreter (   318) [] document default language is en
 22261 [aa-b781-39b0861c2faf] DEBUG erpreter.grammar.GrammarLoader (   123) [] loading internal grammar
 22266 [aa-b781-39b0861c2faf] INFO  ntserver.jetty.DocumentStorage (   204) [] initialized document storage for session '7616d765-943a-4daa-b781-39b0861c2faf'
 22268 [aa-b781-39b0861c2faf] INFO  ntserver.jetty.DocumentStorage (   179) [] added grammar document at 'http://192.168.137.1:9595/grammars/7616d765-943a-4daa-b781-39b0861c2faf/1722039625'
 22270 [aa-b781-39b0861c2faf] DEBUG ntserver.jetty.DocumentStorage (   181) [] added document org.jvoicexml.interpreter.grammar.InternalGrammarDocument[http://192.168.137.1:9595/grammars/7616d765-943a-4daa-b781-39b0861c2faf/1722039625,VOICE,null,GBK,<grammar xmlns="http://www.w3.org/2001/06/grammar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" root="OGVOICE168fb9d89c2S000001" version="1.0" xml:lang="en" xsi:schemaLocation="http://www.w3.org/2001/06/grammar http://www.w3.org/TR/speech-grammar/grammar.xsd"><rule id="OGVOICE168fb9d89c2S000001"><one-of><item>red</item><item>blue</item><item>green</item></one-of></rule></grammar>]
 22274 [aa-b781-39b0861c2faf] DEBUG ammar.GrammarIdentifierCentral (   111) [] trying to identify grammar with 'class org.jvoicexml.interpreter.grammar.regex.RegexGrammarIdentifier'
 **22276 [aa-b781-39b0861c2faf] DEBUG ammar.GrammarIdentifierCentral (   120) [] identified grammar with type 'application/grammar+regex'**
 22277 [aa-b781-39b0861c2faf] DEBUG mitem.AbstractGrammarContainer (    88) [] added grammar org.jvoicexml.interpreter.grammar.InternalGrammarDocument[http://192.168.137.1:9595/grammars/7616d765-943a-4daa-b781-39b0861c2faf/1722039625,VOICE,application/grammar+regex,GBK,<grammar xmlns="http://www.w3.org/2001/06/grammar" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" root="OGVOICE168fb9d89c2S000001" version="1.0" xml:lang="en" xsi:schemaLocation="http://www.w3.org/2001/06/grammar http://www.w3.org/TR/speech-grammar/grammar.xsd"><rule id="OGVOICE168fb9d89c2S000001"><one-of><item>red</item><item>blue</item><item>green</item></one-of></rule></grammar>] for field 'color'
 22280 [aa-b781-39b0861c2faf] DEBUG l.interpreter.ActiveGrammarSet (   125) [] added 1 grammar(s) - now containing 1
 22281 [aa-b781-39b0861c2faf] DEBUG VoiceXmlImplementationPlatform (   707) [] obtaining resource 'text' from pool...
 22281 [aa-b781-39b0861c2faf] INFO  ntation.pool.KeyedResourcePool (   118) [] borrowed object of type 'text' (org.jvoicexml.implementation.text.TextSpokenInput)
 22284 [aa-b781-39b0861c2faf] DEBUG ntation.pool.KeyedResourcePool (   123) [] pool has now 1 active/99 idle for key 'text' (org.jvoicexml.implementation.text.TextSpokenInput) after borrow
 22285 [aa-b781-39b0861c2faf] DEBUG VoiceXmlImplementationPlatform (   712) [] connecting external resource (org.jvoicexml.implementation.text.TextSpokenInput).
 22286 [aa-b781-39b0861c2faf] DEBUG VoiceXmlImplementationPlatform (   727) [] ...connected

grammer xml config： jvxml-grammar.xml
`<?xml version="1.0" encoding="UTF-8"?>
<jvxmlgrammar xmlns:beans="http://www.springframework.org/schema/beans"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="jvxml-grammar-0-7.xsd">
  <beans:bean
    class="org.jvoicexml.interpreter.grammar.identifier.SrgsXmlGrammarIdentifier" />
  <beans:bean
    class="org.jvoicexml.interpreter.grammar.identifier.SrgsAbnfGrammarIdentifier" />
  <beans:bean
    class="org.jvoicexml.interpreter.grammar.identifier.JsgfGrammarIdentifier" />
  <beans:bean
    class="org.jvoicexml.interpreter.grammar.identifier.NuanceDynagramBinaryGrammarIdentifier" />
  <beans:bean
    class="org.jvoicexml.interpreter.grammar.identifier.GslGrammarIdentifier" />
</jvxmlgrammar>`

regex-grammar.xml：
`<?xml version="1.0" encoding="UTF-8"?><jvxmlgrammar xmlns:beans="http://www.springframework.org/schema/beans" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jvxml-grammar-0-7.xsd">
  <classpath>lib/org.jvoicexml.interpreter.grammar.regex-0.7.8.jar</classpath>
  <beans:bean class="org.jvoicexml.interpreter.grammar.regex.RegexGrammarIdentifier"/>
</jvxmlgrammar>
`

**Comment by schnelle** [comment]
That is a weird issue. 

The type is considerd to be a hint as per VoiceXML spec. Hence, I try to use this one first. However, the regex identifier should not identify it. This means, that the grammar XML document compile as a valid regular expression.

This should be fixed.

**Comment by schnelle** [comment]
Fixed. Please, retest.
