### ISSUE TITLE
run builds only if they can b compled on the operationg system

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#75]
Some implementation platforms use Microsoft Visual Studio to compile. As this is not available on Linux system the build system shold not try to execute them.

**Comment by David-dp-** [comment]
I believe this still fails, due to a dependency on "msbuild".

**Comment by ModalityZ** [comment]
A problem occurred evaluating project ':org.jvoicexml.implementation.kinect'.
Failed to apply plugin [id 'msbuild']

Could not create task of type 'Msbuild'.
