### ISSUE TITLE
Unable to Import Project into Eclipse

### ISSUE THREAD

**Issue by srikrishnacj** [JVoiceXML/JVoiceXML#8]
Is there any quick start guide to run and learn this project. I know maven and i don't know Ant. Simple ant commands wont work in this project. and also i am Unable to import this project into eclipse. Please guide me where to start

**Comment by schnelle** [comment]
Did you find the user guide and the how to build guide already? http://jvoicexml.sourceforge.net/downloads.html

**Comment by srikrishnacj** [comment]
Thank you. I will take a look at it.
