### ISSUE TITLE
Add Zanzibar

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#82]
The Zanzibar project https://sourceforge.net/p/halef/halef-zanzibar/ that allowed for an integration of JVoiceXML into Asterisk has been abandonned.

Add the source code as a basis for further telephony extensions of JVoiceXML

**Comment by rapgro** [comment]
Sad to read. Thanks for caring.

**Comment by rapgro** [comment]
BTW do you know Hubware? https://hubware.house/de/

**Comment by schnelle** [comment]
What is the relationship of hubware to Zanzibar?

**Comment by rapgro** [comment]
> What is the relationship of hubware to Zanzibar?

I'm not sure but Hubware offers Speech systems, as well.

**Comment by schnelle** [comment]
> > What is the relationship of hubware to Zanzibar?
> 
> I'm not sure but Hubware offers Speech systems, as well.
So, please stay focused to the topic of this issue to also make it easier for the readers of these issues to learn what is going on here.

Thank you.
