### ISSUE TITLE
Variables in a dialog are not lost after a goto

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#84]
The VoiceXML 2.0 spec for the goto elelement https://www.w3.org/TR/voicexml20/#dml5.3.7 states 

> Note that transitioning to another dialog in the current document causes the old dialog's variables to be lost, even in the case where a dialog is transitioning to itself. Transitioning to another document using an absolute or relative URI will likewise drop the old document level variables, even if the new document is the same one that is making the transition. 

Currently, the variables are kept.

**Comment by David-dp-** [comment]
That doesn't apply to variables at the application or session level, I
would think.

**Comment by schnelle** [comment]
Yes. it seems to be limited to goto
