### ISSUE TITLE
building/starting JvoiceXML

### ISSUE THREAD

**Issue by kumartj** [JVoiceXML/JVoiceXML#86]
I have downloaded and done a Gradle build of JvoiceXML. While following the steps on how to start the JVoice Browser, facing an issue.

Steps followed
- changed the platform.xml to enable Text implementation and pasted this in personal-props
- running ant -f configuration.xml in org.jvoicexml folder

Ant build failed as not able to find  any ant file , below is the code.  could not find any build.xml in this directory org.jvoicexml.jndi

 `<target name="-configureJndi" if="${enableJndi}">
        <ant dir="../org.jvoicexml.jndi"
             target="configuration"
             inheritall="false"
             inheritrefs="false" />
    </target>`

**Comment by schnelle** [comment]
Hmmm...ANT has been completely abandonned in favor of gradle. Unfortunately, there are still some fragments in the documentation.

I could clean this up if you help me to spot that fragment that you are referring to.

**Comment by kumartj** [comment]
Thanks for reply.

I was referring to "howTobuild" module it says that one can start the JvoiceXML browser with the ant only and do not start with directly running the script.

I was able to build the project using Gradle successfully . So how do we start the JvoiceXML server? 

I have to run text demo, for that I need to start the JvoiceXML server

**Comment by schnelle** [comment]
Ensure that your copy of the Gradle properties features the following entry

`JVOICEXML_IMPLEMENTATION_TEXT = true`

The main features an application plugin and can be run.

**Comment by kumartj** [comment]
Ok I got this working. It was simple I got confused with multiple start up scripts and ANT documentation.
Steps are simple (for others)
- Complete the Gradle build
- use the tar/zip distribution under the main to start JvoiceXML server
- Test it by running the demo's

**Comment by schnelle** [comment]
Could you please elaborate on "Complete the Gradle build"?

**Comment by kumartj** [comment]
Sorry, for confusing statement. Actually meant to say use Gradle 3.0 to build the project. Once the project is successfully build the main would have a distribution as tar/zip that can be used to start JvoiceXML
