### ISSUE TITLE
Any Other Tutorials To understand Internals And Architecture...?

### ISSUE THREAD

**Issue by srikrishnacj** [JVoiceXML/JVoiceXML#9]
I have very basic knowledge on voice application. with that i am trying to understand VoiceXML Interpreter. How to use JVoiceXml guide is not clear enough for me. is there any other tutorials or blog post available for JVoiceXml to learn its internals and architecture. and also i want to know is there any maven port for this project..

**Comment by schnelle** [comment]
What are you missing exactly?  I can try to improve the tutorial based on your suggestions.

**Comment by srikrishnacj** [comment]
Things like How implementation platform works. how call manager works. when happens when seesion.call() is called. where user input is captured. what is sub project client and client text and there is also implementation.text. Just looking for beginner level tutorial. Its hard for me to browser java docs and understand whats going under the hood. For now i am just looking for Text Only implementation.

**Comment by schnelle** [comment]
OK. I will try to add something like a beginner's tutorial.

**Comment by mainakanyi** [comment]
Can I get the tutorial for android?

**Comment by schnelle** [comment]
Unfortunately, there is no such tutorial. There have been some efforts in the light of student theses to port it to Android, but I do not have any socumentation on that. Sorry about that.

**Comment by michaelplevy** [comment]
Can someone share a link to the current tutorial?

I found userguide.tex in the GitHub repository. Is this the right place to start? Is there  a PDF version available somewhere?

The documentation link from http://jvoicexml.sourceforge.net/index.php goes to http://sourceforge.net/apps/mediawiki/jvoicexml/index.php?title=Main_Page which seems to be broken. Is there a better place to find documentation?

**Comment by michaelplevy** [comment]
Ok, links are still broken, but I did find https://sourceforge.net/projects/jvoicexml/files/

**Comment by schnelle** [comment]
Please, send me your email address to dirk dot schnelle at jvoicexml dot org and I could send you the current snapshot of the user guide.

**Comment by michaelplevy** [comment]
Thanks Dirk. I found it at http://sourceforge.net/projects/jvoicexml/files/userguide/0.7.6.GA/jvxml-userguide-0.7.6.GA.pdf and also built it from Lex.

**Comment by schnelle** [comment]
OK. Drop me a note if you need more help.

**Comment by mylater** [comment]
Hey there,
I still can‘t execute Callmanager project on Android branch right way, is any sugesstion for me ?

**Comment by schnelle** [comment]
Please, create another issue related to your exact problem and do not reuse this one as I have the impression that the focus is somewhat different.

Thanks!
