### ISSUE TITLE
Form:Block elements heard twice unless in prompt element

### ISSUE THREAD

**Issue by karlnicholas** [JVoiceXML/JVoiceXML#91]
Just new here and checking out the demos. I notice that the helloworld demo says "Hello World" twice presumably because the text is in a <block> tag but not in a <prompt> tag. The demo says "Goodbye" only once because the text is in a <prompt> tag. Is this expected behavior?

**Comment by schnelle** [comment]
This is fixed by issue #85

**Comment by karlnicholas** [comment]
Okay.
