### ISSUE TITLE
Support for AMQP / RabbitMQ

### ISSUE THREAD

**Issue by rapgro** [JVoiceXML/JVoiceXML#96]
A long outstanding request. Would it be possible to have native support for AMQP with (any new) one of an implementation? I tried to start something but never managed to get response from core development. My work did not get even further and I plan to discontinue at all because of really lack of time but I still want to let you all know.
https://gitlab.com/voice-mediator/jvxml-amqp

See especially in this paper:
https://academiccommons.columbia.edu/download/fedora_content/download/ac:165655/content/Virtualization.pdf

**Comment by rapgro** [comment]
RabbitMQ java client seems to be the library to use.

**Comment by rapgro** [comment]
https://github.com/JVoiceXML/JVoiceXML/issues/14

**Comment by schnelle** [comment]
I see that you intent to have this as an implementation platform. This means

- receiving inputs
- sending outputs

via AMQP.

What would be the purpose of that and who should be the receiver of those messages in which format?

**Comment by schnelle** [comment]
It seems that there is no actual use case behind this request. Closing that issue.

**Comment by rapgro** [comment]
Lyra is a high-availability RabbitMQ client (for AMQP as the used protocol).
https://github.com/jhalterman/lyra

**Comment by schnelle** [comment]
A clear use case is still missing. I already asked twicve but still did not get any meaningful answer.

**Comment by David-dp-** [comment]
Regarding a use-case, do you have in mind something like: It should be
possible to send information to jvxml's FIA, without the jvxml app
requesting it, so that grammars and prompts might be interrupted and the
app directed to another form or doc location?

**Comment by rapgro** [comment]
Can you do MMI? https://de.slideshare.net/Abd0/multimodal-interaction-an-introduction

**Comment by schnelle** [comment]
There are currently 3 protocols available in JVoiceXML to interact in MMI
- HTTP
- uMundo (an abstraction over ZweroMQ)
- Sockets

What would be the benefit of supporting a 4th protocol?

**Comment by David-dp-** [comment]
Where can one read more about how to use these protocols with jvxml?

**Comment by schnelle** [comment]
These are implemented as CallManagers and can currently not be used with telephony environments. See the corresponding call managers for a reference

- https://github.com/JVoiceXML/JVoiceXML/tree/master/org.jvoicexml.callmanager.mmi
- https://github.com/JVoiceXML/JVoiceXML/tree/master/org.jvoicexml.callmanager.mmi.http
- https://github.com/JVoiceXML/JVoiceXML/tree/master/org.jvoicexml.callmanager.mmi.socket
- https://github.com/JVoiceXML/JVoiceXML/tree/master/org.jvoicexml.callmanager.mmi.umundo

 Unfortunately, there is no other documentation available

**Comment by rapgro** [comment]
> uMundo (an abstraction over ZeroMQ)
In case there's a typo and you mean ZeroMQ instead, then you can consider my request as obsolete. ZeroMQ is similiar to AMQP.

**Comment by rapgro** [comment]
Well, as somewhere else stated I've somehow possible experiments with more complexity in mind.
E.g. Connect any monitoring system like discussed in https://github.com/dnaeon/py-vpoller/issues/226
