### ISSUE TITLE
Embbedded demo does not work

### ISSUE THREAD

**Issue by schnelle** [JVoiceXML/JVoiceXML#97]
JVoiceXML has received several changes that have not been adapted to the embedded demo. As a consequnce the embedded demo doe not work any longer

**Comment by rapgro** [comment]
What's the (planned) effort so far for a continuous integration framework with automatic execution of unit tests?

**Comment by schnelle** [comment]
I do not see that this is related to this issue. It may help to detect it earlier but I simply did not pay much attention on that demo.

**Comment by rapgro** [comment]
Why not run the demo inside CI then, within a mocked environment?

**Comment by schnelle** [comment]
Maybe, it has to be fixed first to run at all.
